auto_apms_examples:
  auto_apms::ops_engine::AsyncPrecondition:
  CreateAlternateLandingMission:

auto_apms:
  ThrowException:
  ArmAction: "arm_disarm"
  DisarmAction: "arm_disarm"
  EnableHoldAction: "enable_hold"
  GoToAction: "go_to"
  GoToVectorAction: "go_to"
  LandAction: "land"
  RTLAction: "rtl"
  TakeoffAction: "takeoff"
  UploadBehaviorTreeAction: "mission_manager/upload"
  ResumeExecutorAction: "mission_manager/command"
  HaltExecutorAction: "mission_manager/command"
  ReadGlobalPosition: "/fmu/out/vehicle_global_position"