auto_apms:
  LoadBehaviorTreeAction:
  ArmAction: "arm_disarm"
  DisarmAction: "arm_disarm"
  EnableHoldAction: "enable_hold"
  TakeoffAction: "takeoff"
  LaunchExecutorAction: ""
  UploadBehaviorTreeAction: ""