BRINGUP:
  - auto_apms_examples::bringup::PX4ContingencyMissionBringUp

MISSION:
  - auto_apms_examples::mission::PX4ContingencyMission

CONTINGENCY:
  auto_apms_examples::contingency_hold::ContingencyHandler:
    - auto_apms_examples::contingency_hold::ContingencyMonitor

EMERGENCY:

SHUTDOWN:
  - auto_apms_examples::shutdown::PX4ContingencyMissionShutDown
