BRINGUP:
  - auto_apms_examples::bringup::PX4ContingencyMissionBringUp

MISSION:
  - auto_apms_examples::mission::PX4ContingencyMission

CONTINGENCY:
  auto_apms_examples::contingency_land::ContingencyMonitor: auto_apms_examples::contingency_land::ContingencyHandler
  auto_apms_examples::contingency_hold::ContingencyMonitor: auto_apms_examples::contingency_hold::ContingencyHandler

EMERGENCY:
  auto_apms_examples::emergency_rtl::EmergencyMonitor: auto_apms_examples::emergency_rtl::EmergencyHandler

SHUTDOWN:
  - auto_apms_examples::shutdown::PX4ContingencyMissionShutDown
