# Request
string tree_identity
bool attach true
---
# Result
uint8 TREE_RESULT_NOT_SET=0
uint8 TREE_RESULT_SUCCESS=1
uint8 TREE_RESULT_FAILURE=2

uint8 tree_result 0
string terminated_tree_identity
string termination_message
---
# Feedback
string execution_state_str
string running_tree_identity
string running_action_name
float64 running_action_timestamp