AsyncPrecondition:
  class_name: auto_apms::ops_engine::AsyncPrecondition

CreateAlternateLandingMission:
  class_name: auto_apms::ops_engine::CreateAlternateLandingMission

ThrowException:
  class_name: auto_apms_behavior_tree::ThrowException

Arm:
  class_name: auto_apms_px4::ArmAction
  port: arm_disarm

Disarm:
  class_name: auto_apms_px4::DisarmAction
  port: arm_disarm

EnableHold:
  class_name: auto_apms_px4::EnableHoldAction
  port: enable_hold

GoTo:
  class_name: auto_apms_px4::GoToAction
  port: go_to

GoToVector:
  class_name: auto_apms_px4::GoToAction
  port: go_to

Land:
  class_name: auto_apms_px4::LandAction
  port: land

Takeoff:
  class_name: auto_apms_px4::TakeoffAction
  port: takeoff

RTL:
  class_name: auto_apms_px4::RTLAction
  port: rtl

UploadBehaviorTree:
  class_name: auto_apms_behavior_tree::UploadBehaviorTreeAction
  port: mission_manager/upload

ResumeExecutor:
  class_name: auto_apms_behavior_tree::ResumeExecutor
  port: mission_manager/command

HaltExecutor:
  class_name: auto_apms_behavior_tree::HaltExecutor
  port: mission_manager/command

ReadGlobalPosition:
  class_name: auto_apms_px4::ReadGlobalPosition
  port: /fmu/out/vehicle_global_position
