Arm:
  class_name: auto_apms_px4::ArmAction
  port: arm_disarm

Disarm:
  class_name: auto_apms_px4::DisarmAction
  port: arm_disarm

EnableHold:
  class_name: auto_apms_px4::EnableHoldAction
  port: enable_hold

GoTo:
  class_name: auto_apms_px4::GoToAction
  port: go_to

Land:
  class_name: auto_apms_px4::LandAction
  port: land

Takeoff:
  class_name: auto_apms_px4::TakeoffAction
  port: takeoff

RTL:
  class_name: auto_apms_px4::RTLAction
  port: rtl
