LoadBehaviorTree:
  class_name: auto_apms_behavior_tree::LoadBehaviorTreeAction

Arm:
  class_name: auto_apms_px4::ArmAction
  port: arm_disarm

Disarm:
  class_name: auto_apms_px4::DisarmAction
  port: arm_disarm

EnableHold:
  class_name: auto_apms_px4::EnableHoldAction
  port: enable_hold

Takeoff:
  class_name: auto_apms_px4::TakeoffAction
  port: takeoff

LaunchExecutor:
  class_name: auto_apms_behavior_tree::StartExecutor

UploadBehaviorTree:
  class_name: auto_apms_behavior_tree::UploadBehaviorTreeAction
