GetSystemState:
  class_name: auto_apms::ops_engine::GetSystemState
  port: system_state

IsApproachingLanding:
  class_name: auto_apms::ops_engine::IsApproachingLanding
  port: landing_approach

IsLandingSiteClear:
  class_name: auto_apms::ops_engine::IsLandingSiteClear
  port: landing_site_status
