if(DEFINED _PX4_BEHAVIOR_BT_NODE_PLUGINS__RESOURCE_FILE)
    ament_index_register_resource("${_PX4_BEHAVIOR_BT_NODE_PLUGINS__RESOURCE_TYPE_NAME}" CONTENT "${_PX4_BEHAVIOR_BT_NODE_PLUGINS__RESOURCE_FILE}")
endif()
if(DEFINED _PX4_BEHAVIOR_BEHAVIOR_TREE__RESOURCE_FILE)
    ament_index_register_resource("${_PX4_BEHAVIOR_BEHAVIOR_TREE__RESOURCE_TYPE_NAME}" CONTENT "${_PX4_BEHAVIOR_BEHAVIOR_TREE__RESOURCE_FILE}")
endif()

