if(DEFINED _PX4_BEHAVIOR_BT_NODE_PLUGINS_RESOURCE_FILE)
    ament_index_register_resource("${_PX4_BEHAVIOR_BT_NODE_PLUGINS_RESOURCE_TYPE_NAME}" CONTENT "${_PX4_BEHAVIOR_BT_NODE_PLUGINS_RESOURCE_FILE}")
endif()

