name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Test
        id: ros-build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: px4_behavior
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: humble
          vcs-repo-file-url: $GITHUB_WORKSPACE/dependencies.repos
          no-symlink-install: true
          colcon-defaults: |
            {
              "test": {
                "packages-select": [
                  "px4_behavior"
                ],
                "ctest-args": [
                  "-R", "px4_behavior_unit_tests"
                ]
              }
            }
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs
          path: ${{ steps.ros-build.outputs.ros-workspace-directory-name }}/log
        if: always() # upload the logs even when the build fails
