name: Jazzy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build_and_test:
    uses: ./.github/workflows/build-and-test-reusable.yaml
    with:
      ros_distribution: jazzy
      docker_image: ubuntu:noble
