name: ROS 2 Jazzy

on:
  push:
    branches:
      - jazzy
  pull_request:
    branches:
      - "*"

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        id: ros-build
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: jazzy
          no-symlink-install: true
          code-coverage: false
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_BUILD_TYPE=Release",
                  "-DBUILD_TESTING=ON",
                ]
              },
              "test": {
                "ctest-args": [
                  "-R", "auto_apms_\\S*_unit_tests"
                ]
              }
            }
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs
          path: ${{ steps.ros-build.outputs.ros-workspace-directory-name }}/log
        if: always() # upload the logs even when the build fails

      - name: Generate Behavior Tree Node Reference
        if: github.event_name == 'push'
        shell: bash
        run: |
          source ${{ steps.ros-build.outputs.ros-workspace-directory-name }}/install/setup.bash
          ros2 run auto_apms_behavior_tree_core create_node_reference_markdown create_node_reference_markdown_output.md include_native auto_apms_behavior_tree::behavior_tree_nodes auto_apms_simulation::behavior_tree_nodes

      - name: Checkout Documentation Repo
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: robin-mueller/auto-apms-guide
          token: ${{ secrets.DOCS_REPO_PAT }}
          path: docs-repo
          ref: master

      - name: Copy Updated Docs
        if: github.event_name == 'push'
        run: |
          cp create_node_reference_markdown_output.md docs-repo/src/reference/create_node_reference_markdown_output.md

      - name: Commit and Push Documentation
        if: github.event_name == 'push'
        run: |
          cd docs-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update behavior tree node reference"
            git push
          fi