name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint using pre-commit
    runs-on: ubuntu-22.04
    container:
      image: ros:humble-ros-base-jammy
    steps:
      - name: Install ROS test dependencies
        run: rosdep update && rosdep install -t test --from-paths "${GITHUB_WORKSPACE}/src/px4_behavior"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
