name: Rolling

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build_and_test:
    uses: ./.github/workflows/build-and-test-reusable.yaml
    with:
      ros_distribution: rolling
      docker_image: ubuntu:noble

  update_node_reference:
    name: Update BT Node Reference Docs
    runs-on: ubuntu-latest
    needs: build_and_test # Only run this job after the build_and_test job has completed successfully.
    if: github.event_name == 'push' # Don't run this job on pull requests, only on pushes.
    container:
      image: ubuntu:noble
      env:
        PIP_BREAK_SYSTEM_PACKAGES: 1 # Allow pip to install system packages if needed.
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build workspace
        id: ros-build
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          target-ros2-distro: rolling
          coverage-result: false
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                  "-DCMAKE_BUILD_TYPE=Release",
                  "-DBUILD_TESTING=OFF"
                ]
              }
            }

      - name: Generate Behavior Tree Node Reference
        shell: bash
        run: |
          source ${{ steps.ros-build.outputs.ros-workspace-directory-name }}/install/setup.bash
          ros2 run auto_apms_behavior_tree_core create_node_reference_markdown create_node_reference_markdown_output.md include_native auto_apms_behavior_tree::behavior_tree_nodes auto_apms_simulation::behavior_tree_nodes

      - name: Checkout Documentation Repo
        uses: actions/checkout@v4
        with:
          repository: robin-mueller/auto-apms-guide
          token: ${{ secrets.DOCS_REPO_PAT }}
          path: docs-repo
          ref: master

      - name: Copy Updated Docs
        run: |
          cp create_node_reference_markdown_output.md docs-repo/src/reference/create_node_reference_markdown_output.md

      - name: Commit and Push Documentation
        run: |
          cd docs-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update behavior tree node reference"
            git push
          fi
